### ISSUE TITLE
Is this website live?

### ISSUE THREAD

**Issue by jonyTF** [Rahix/tf2-voicelines#2]
Hi, 

Have you published this website anywhere for others to access? This sounds like a really cool idea and something that I think I could really benefit from (especially for finding voice lines to use in SFM videos).

Thanks!

**Comment by Rahix** [comment]
Yes!  I never got around to giving it a proper URL though, so it's available under the awkward

https://rahix.de/~tf2/voicelines/

for now ...

**Comment by jonyTF** [comment]
ok cool thanks!
